### ISSUE TITLE
A little bug i thought would be in the update...

### ISSUE THREAD

**Issue by UltraMafic** [capasha/eeditor#1]
So a while ago i started using EEditor, everything works great by the way! There is just one problem though. The 'Gravity Effect' doesn't have a value changer! D:

It isn't a big issue, but i do like to only edit my worlds in EEditor. I would have to go into the game and customize the Gravity Effect myself, which i don't really like to do because it wouldn't load the same in EEditor.

Please fix this bug, and again, amazing project! I really like how it came out so far!

**Comment by capasha** [comment]
When you right-click on the block inside the workarea in EEditor does it change the directions?
When you right-click on the block in the blockbar do you see a menu to choose directions?

Test these and report back.

**Comment by capasha** [comment]
I have noticed that right-click in workarea doesn't work at all. This will be fixed in the new update.
