### ISSUE TITLE
EEditor won't upload the changes I've made to my level

### ISSUE THREAD

**Issue by minermaniac447** [capasha/eeditor#2]
I have EEditor singed in as my account (minecraftawesomeness), and I can't get it to upload to my world. I've given it the code and the world ID, and whenever I click the button for it to upload, it **says** that it's uploaded, but I check the world and none of the changes are there.

**Comment by capasha** [comment]
I came up with that sending NPC without name is crashing EEditor. This will be fixed in the next update.
So people, don't add a NPC without a name till I fix this.
